version: '3'
services:
  neo4j:
    image: neo4j
    environment:
      NEO4J_AUTH: neo4j/neo-spring-demo
    ports:
    - "7474:7474"
    - "7687:7687"
  api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      NEO4J_URI: bolt://neo4j:7687
      NEO4J_PASSWORD: neo-spring-demo
    depends_on:
      - neo4j
    ports:
    - "8080:8080"